--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5
-- Dumped by pg_dump version 12.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
--
-- Name: sclad; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE sclad;
ALTER DATABASE sclad OWNER TO postgres;

\connect sclad

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: authorities; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.authorities (
    id bigint,
    username character varying(50) NOT NULL,
    authority character varying(50) NOT NULL
);


ALTER TABLE public.authorities OWNER TO sclad;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO sclad;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO sclad;

--
-- Name: defect_report; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.defect_report (
    id bigint NOT NULL,
    date_of_discovery date NOT NULL,
    device_serial_number character varying(255) NOT NULL,
    fault_description character varying(255),
    attachment_id bigint,
    device_id bigint NOT NULL
);


ALTER TABLE public.defect_report OWNER TO sclad;

--
-- Name: defect_report_id_seq; Type: SEQUENCE; Schema: public; Owner: sclad
--

ALTER TABLE public.defect_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.defect_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.device (
    id bigint NOT NULL,
    device_type character varying(255) DEFAULT 'NOTEBOOK'::character varying,
    is_reordered boolean DEFAULT false,
    product_code character varying(255) NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer DEFAULT 10 NOT NULL,
    quantity_threshold integer DEFAULT 1
);


ALTER TABLE public.device OWNER TO sclad;

--
-- Name: device_id_seq; Type: SEQUENCE; Schema: public; Owner: sclad
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restock_order; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.restock_order (
    id bigint NOT NULL,
    device_type character varying(255),
    product_name character varying(255),
    quantity_to_reorder integer NOT NULL,
    send_notification boolean,
    device_id bigint NOT NULL
);


ALTER TABLE public.restock_order OWNER TO sclad;

--
-- Name: restock_order_id_seq; Type: SEQUENCE; Schema: public; Owner: sclad
--

ALTER TABLE public.restock_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restock_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploaded_file; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.uploaded_file (
    id bigint NOT NULL,
    data oid,
    file_name character varying(255),
    file_type character varying(255)
);


ALTER TABLE public.uploaded_file OWNER TO sclad;

--
-- Name: uploaded_file_id_seq; Type: SEQUENCE; Schema: public; Owner: sclad
--

ALTER TABLE public.uploaded_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uploaded_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: sclad
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(100) NOT NULL,
    username character varying(50) NOT NULL,
    enabled smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.users OWNER TO sclad;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: sclad
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: authorities; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.authorities (id, username, authority) FROM stdin;
\N	admin	ROLE_ADMIN
\N	user	ROLE_USER
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
createDevice	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.30033	1	EXECUTED	8:0c19cb2cb4ec1ff95973bf2ca301993e	createTable tableName=device		\N	3.8.5	\N	\N	7432023228
createRestockOrder	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.322783	2	EXECUTED	8:f1671681c1b6d8f6fb13b0a915c5575a	createTable tableName=restock_order		\N	3.8.5	\N	\N	7432023228
createUploadedFile	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.342439	3	EXECUTED	8:f3cb574d8d1de7516710624cd7556dd5	createTable tableName=uploaded_file		\N	3.8.5	\N	\N	7432023228
createDefectReport	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.366463	4	EXECUTED	8:8cc8a57893cfa4416a6d4e49478e0d71	createTable tableName=defect_report		\N	3.8.5	\N	\N	7432023228
createRole	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.380289	5	EXECUTED	8:17df2639b80434017903647b35a8eda6	createTable tableName=authorities		\N	3.8.5	\N	\N	7432023228
createUser	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.391422	6	EXECUTED	8:f62707337bc4cb582a4a0842956391b4	createTable tableName=users		\N	3.8.5	\N	\N	7432023228
set_authorities_fk	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.401124	7	EXECUTED	8:e3848c2e0b077e02fb5dce59faa5a7ca	addForeignKeyConstraint baseTableName=authorities, constraintName=fk_authorities_username, referencedTableName=users		\N	3.8.5	\N	\N	7432023228
set_index_authorities	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.410846	8	EXECUTED	8:25b7dde14b24bd727bd34c11b8891a67	createIndex indexName=idx_authorities, tableName=authorities		\N	3.8.5	\N	\N	7432023228
set_defect_report_fkeys	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.418624	9	EXECUTED	8:6d3207dd24721ac88f45e3dc5b8cf6ea	addForeignKeyConstraint baseTableName=defect_report, constraintName=fk_defect_report_attachment, referencedTableName=uploaded_file; addForeignKeyConstraint baseTableName=defect_report, constraintName=fk_defect_report_device, referencedTableName=de...		\N	3.8.5	\N	\N	7432023228
set_restock_order_fkeys	lmisaga	classpath:/db/changelog/./001.createTables.xml	2021-11-20 19:13:43.424174	10	EXECUTED	8:1ed49c61b852406db110dfb6f13ffa70	addForeignKeyConstraint baseTableName=restock_order, constraintName=fk_restock_order_device, referencedTableName=device		\N	3.8.5	\N	\N	7432023228
createDummyDataDevice	lmisaga	classpath:/db/changelog/./002.createDummyData.xml	2021-11-20 19:13:43.430902	11	EXECUTED	8:b5aeb95a66a50d9bfaa031d3114811af	insert tableName=device; insert tableName=device; insert tableName=device; insert tableName=device		\N	3.8.5	\N	\N	7432023228
createDummyDataRestockOrder	lmisaga	classpath:/db/changelog/./002.createDummyData.xml	2021-11-20 19:13:43.438789	12	EXECUTED	8:80a8bf30ec5519ec65e666cf253ed178	insert tableName=restock_order; insert tableName=restock_order		\N	3.8.5	\N	\N	7432023228
createDummyDataFaultReport	lmisaga	classpath:/db/changelog/./002.createDummyData.xml	2021-11-20 19:13:43.447207	13	EXECUTED	8:832ba3e0fc6e1c26677b9004cf3982b6	insert tableName=defect_report; insert tableName=defect_report		\N	3.8.5	\N	\N	7432023228
createDummyAdmin	lmisaga	classpath:/db/changelog/./002.createDummyData.xml	2021-11-20 19:13:43.453825	14	EXECUTED	8:e691ab4f47a4f8dc710054313e1dc212	insert tableName=users; insert tableName=authorities		\N	3.8.5	\N	\N	7432023228
createDummyUser	lmisaga	classpath:/db/changelog/./002.createDummyData.xml	2021-11-20 19:13:43.456779	15	EXECUTED	8:e0d067c4c148d3042a544383ce264ba7	insert tableName=users; insert tableName=authorities		\N	3.8.5	\N	\N	7432023228
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: defect_report; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.defect_report (id, date_of_discovery, device_serial_number, fault_description, attachment_id, device_id) FROM stdin;
1	2020-02-11	SN_35263473HAFD	The device is broken. Pls fix	\N	1
2	2020-03-03	SN_BFB7453AFB	Another device broken smh	\N	2
\.


--
-- Data for Name: device; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.device (id, device_type, is_reordered, product_code, product_name, quantity, quantity_threshold) FROM stdin;
3	SMARTPHONE	f	REORDERED1_SMARTPHONE xd	Product Number 3	2	5
2	NOTEBOOK	f	afsadghbnhdadg_02	Product Number 2	0	1
1	NOTEBOOK	f	aSDFSADFSADf_01	Product Number 1	59	2
4	ALL_IN_ONE	f	REORDERED2_ALLINONE xd	Product Number 4	3	4
\.


--
-- Data for Name: restock_order; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.restock_order (id, device_type, product_name, quantity_to_reorder, send_notification, device_id) FROM stdin;
\.


--
-- Data for Name: uploaded_file; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.uploaded_file (id, data, file_name, file_type) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: sclad
--

COPY public.users (id, email, password, username, enabled) FROM stdin;
1	admin@sClad.com	$2a$10$rXWSOtLuCpleuF3tUUztj.G4mDhnE3gR267vavK3tmok4iwdb1jmS	admin	1
2	user@sClad.com	$2a$10$MxKHCVEoDimY97SUxHfPKOhR5jccXdCMbHX6rJKMwHvHkzv/SgArC	user	1
\.


--
-- Name: defect_report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sclad
--

SELECT pg_catalog.setval('public.defect_report_id_seq', 2, true);


--
-- Name: device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sclad
--

SELECT pg_catalog.setval('public.device_id_seq', 4, true);


--
-- Name: restock_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sclad
--

SELECT pg_catalog.setval('public.restock_order_id_seq', 34, true);


--
-- Name: uploaded_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sclad
--

SELECT pg_catalog.setval('public.uploaded_file_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sclad
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: authorities authorities_username_key; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.authorities
    ADD CONSTRAINT authorities_username_key UNIQUE (username);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: defect_report defect_report_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.defect_report
    ADD CONSTRAINT defect_report_pkey PRIMARY KEY (id);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);


--
-- Name: restock_order restock_order_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.restock_order
    ADD CONSTRAINT restock_order_pkey PRIMARY KEY (id);


--
-- Name: uploaded_file uploaded_file_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);


--
-- Name: idx_authorities; Type: INDEX; Schema: public; Owner: sclad
--

CREATE INDEX idx_authorities ON public.authorities USING btree (username, authority);


--
-- Name: authorities fk_authorities_username; Type: FK CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.authorities
    ADD CONSTRAINT fk_authorities_username FOREIGN KEY (username) REFERENCES public.users(username) ON DELETE CASCADE;


--
-- Name: defect_report fk_defect_report_attachment; Type: FK CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.defect_report
    ADD CONSTRAINT fk_defect_report_attachment FOREIGN KEY (attachment_id) REFERENCES public.uploaded_file(id) ON DELETE CASCADE;


--
-- Name: defect_report fk_defect_report_device; Type: FK CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.defect_report
    ADD CONSTRAINT fk_defect_report_device FOREIGN KEY (device_id) REFERENCES public.device(id);


--
-- Name: restock_order fk_restock_order_device; Type: FK CONSTRAINT; Schema: public; Owner: sclad
--

ALTER TABLE ONLY public.restock_order
    ADD CONSTRAINT fk_restock_order_device FOREIGN KEY (device_id) REFERENCES public.device(id);


--
-- PostgreSQL database dump complete
--

